### ISSUE TITLE
Incorrect parameter name

### ISSUE THREAD

**Issue by stephlocke** [DoubleYouGTT/hubspot#60]
I just hot fixed the parameter for `get_contacts()`. It seems that the incorrect label of `properties` was being added, not `property`. All the other getters with functions should be checked for the same issue.

f7a245c1f99de5971865fc88234d88b2a2bd1c3a

**Comment by stephlocke** [comment]
I also don't know how to make sure the tests pass as I  *think* they're erroring due to object changes now 🙊

**Comment by maelle** [comment]
What should work is for you to delete https://github.com/lockedata/hubspot/blob/master/tests/fixtures/get_contacts.yml then run the tests (but make sure you use no own key no own token, i.e. invalidate the env variable of the token and set the key to demo via hubspot_key_set) to create the updated cassette. (Otherwise your creds would be in the cassette).

**Comment by maelle** [comment]
I only see "properties" in https://developers.hubspot.com/docs/methods/deals/get-all-deals and https://developers.hubspot.com/docs/methods/companies/get-all-companies where it is correct, so I think there's no further problem.

The tests no longer fail.
